---
  - template: src=rtwsrc.j2 dest=/etc/rtwsrc owner=rtws group=rtws mode=0644 force=yes
  
  - file: path={{ dir }} owner=rtws group=rtws mode=0775 state=directory recurse=yes
    loop:
      - /usr/local/rtws/properties
      - /usr/local/rtws/conf
    loop_control:
      loop_var: dir
      
  - template: src=aws.j2 dest={{ dir }}/aws.properties owner=rtws group=rtws mode=0644 force=yes
    loop:
      - /usr/local/rtws/properties
      - /usr/local/rtws/conf
    loop_control:
      loop_var: dir
  
  - file: path={{ rtws_appfs }}/configuration/{{ rtws_domain }} owner=rtws group=rtws mode=0775 state=directory recurse=yes
  
  - name: Ensure correct permissions on {{ rtws_appfs }}/configuration
    file: path={{ rtws_appfs }}/configuration owner=rtws group=rtws mode=0755 state=directory recurse=yes  
  
  # The usual setup for properties     
  - file: path=/usr/local/rtws/properties owner=rtws group=rtws mode=0775 state=directory recurse=no   

  - file: path=/usr/local/rtws/conf owner=rtws group=rtws mode=0775 state=directory recurse=no
  
  - unarchive: src={{ rtws_appfs }}/configuration/{{ rtws_domain }}/deleidos-rtws-common-properties-conf.tar.gz dest=/usr/local/rtws/properties
  
  - unarchive: src={{ rtws_appfs }}/configuration/{{ rtws_domain }}/deleidos-rtws-common-conf-conf.tar.gz dest=/usr/local/rtws/conf
  
  - file: path={{ rtws_appfs }}/configuration/{{ rtws_domain }}/sw state=absent 
    loop:
      - deleidos-rtws-common-properties-conf.tar.gz
      - deleidos-rtws-common-conf-conf.tar.gz
    loop_control:
      loop_var: sw
      
  - replace: dest=/usr/local/rtws/properties/rtws-common.properties regexp='rtws.internal.webapp.unsecured.port=80' replace='rtws.internal.webapp.unsecured.port=81' backup=no
  

  - name: Ensure /usr/local/rtws has the correct permissions
    file: path=/usr/local/rtws owner=rtws group=rtws mode=0775 state=directory recurse=yes