version: 2
jobs:
  build:
    docker:
      - image: jmal98/digitaledge-build-image:7-jdk
    resource_class: medium+

    working_directory: ~/repo

    environment:
      M2_OPTS: -Xms128m -Xmx2048m -XX:PermSize=64m -XX:MaxPermSize=256m -Xss4m
      MAVEN_OPTS: -Xms128m -Xmx2048m -XX:PermSize=64m -XX:MaxPermSize=256m -Xss4m

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "parent/pom.xml" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: cd .. && git clone https://github.com/jmal98/digitaledge-plugins.git && ls -ltrh

      # Ensure buildtools are present
      - run: cd ../digitaledge-plugins && ./mvnw -f plugin-validator/pom.xml clean install -B

      - run: cd ../digitaledge-plugins && ./mvnw -f plugins-assembly-descriptor/pom.xml clean install -B

      # Ensure project reactor lines up
      - run: ./mvnw -f parent/pom.xml clean -B

      - run: ls -ltra ~/.m2

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "parent/pom.xml" }}

      # Build
      - run: ./mvnw -f commons-systems/pom.xml clean compile -B -DIN_EUCA_ENV=false -Dincrement=true

      - run: ./mvnw -f parent/pom.xml install -Dincrement=false -DskipTests -B

      # run tests!
      - run: mkdir ~/repo/junit

      - run:
           command: ./mvnw -f parent/pom.xml test -B
           no_output_timeout: 4h

      - run: find ~/repo/ -name 'TEST*.xml' | xargs -I {} cp -fv {} ~/repo/junit/.

      - store_test_results:
          path: ~/repo/junit
