version: 2
jobs:
  build:
    machine: true

    working_directory: ~/repo

    environment:
      M2_OPTS: -Xms128m -Xmx5120m -XX:PermSize=64m -XX:MaxPermSize=256m -Xss4m
      MAVEN_OPTS: -Xms128m -Xmx5120m -XX:PermSize=64m -XX:MaxPermSize=256m -Xss4m
      JAVA_HOME: /usr/lib/jvm/java-7-openjdk-amd64

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "parent/pom.xml" }}
          # fallback to using the latest cache if no exact match is found
          #- v1-dependencies-

      - run:
          name: Install packages required for build
          command: sudo apt-get update && sudo apt-get install -y gcc libssl-dev libffi-dev make openjdk-7-jdk python-dev python-setuptools python-yaml

      - run:
          name: Install Ansible
          command: easy_install ansible==2.6.0

      - run:
          name: Clone core plugins repository
          command: cd .. && git clone https://github.com/jmal98/digitaledge-plugins.git && ls -ltrh

      - run: whoami

      - run:
          name: Ensure buildtools are present
          command: cd ../digitaledge-plugins && ./mvnw -f plugin-validator/pom.xml clean install -B

      - run:
          name: Ensure custom descriptors are present
          command: cd ../digitaledge-plugins && ./mvnw -f plugins-assembly-descriptor/pom.xml clean install -B

      - run:
          name: Ensure project reactor lines up
          command: ./mvnw -f parent/pom.xml clean -B

      - run: ls -ltra ~/.m2

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "parent/pom.xml" }}

      - run:
          name: Increment artifact timestamp label
          command: ./mvnw -f commons-systems/pom.xml clean compile -B -DIN_EUCA_ENV=false -Dincrement=true

      - run:
          name: Build/Test
          command: ./mvnw -f parent/pom.xml install -Dincrement=false -B
          no_output_timeout: 4h

      - run:
          name: Copy test results to Circleci parsing location
          command: mkdir ~/repo/junit && find ~/repo/ -name 'TEST*.xml' | xargs -I {} cp -fv {} ~/repo/junit/.

      - store_test_results:
          path: ~/repo/junit
