version: 2
jobs:
  build:
    docker:
      - image: openjdk:7-jdk

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout

      # TODO relocate to include Ansible dependency in custom image
      - run: apt-get update && apt-get install -y python-setuptools python-dev python-yaml libssl-dev libffi-dev

      - run: easy_install ansible==2.6.0

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "parent/pom.xml" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: cd .. && git clone https://github.com/jmal98/digitaledge-plugins.git && ls -ltrh

      # Ensure buildtools are present
      - run: cd ../digitaledge-plugins && ./mvnw -f plugin-validator/pom.xml clean install -B

      - run: cd ../digitaledge-plugins && ./mvnw -f plugins-assembly-descriptor/pom.xml clean install -B

      # Ensure project reactor lines up
      - run: ./mvnw -f parent/pom.xml clean -B

      # Build
      - run: ./mvnw -f parent/pom.xml install -DskipTests -B

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "parent/pom.xml" }}

      # run tests!
      - run: mkdir ~/repo/junit

      - run: ./mvnw -f parent/pom.xml test -B

      - run: find ~/repo/ -name 'TEST*.xml' | xargs -I {} cp -fv {} ~/repo/junit/.

      - store_test_results:
          path: ~/repo/junit
