---  
  # Setup: /usr/local/rtws 
  - file: path=/usr/local/rtws owner=rtws group=rtws mode=0775 state=directory recurse=no
  
  - file: path=/usr/local/rtws/boot/lib owner=rtws group=rtws mode=0775 state=directory recurse=no
    
  - name: Extracting release to /usr/local/rtws
    unarchive: src={{ rtws_appfs }}/release/{{ rtws_release }}/{{ sw }} dest=/usr/local/rtws/
    loop:
      - deleidos-rtws-commons-core.tar.gz
      - deleidos-rtws-boot-apps.tar.gz
      - deleidos-rtws-cert-auth-dist.tar.gz
    loop_control:
      loop_var: sw
      
  
  - name: Removing release tar.gz(s) 
    file: path={{ rtws_appfs }}/release/{{ rtws_release }}/{{ sw }} state=absent
    loop:
      - deleidos-rtws-commons-core.tar.gz
      - deleidos-rtws-boot-apps.tar.gz
      - deleidos-rtws-cert-auth-dist.tar.gz
    loop_control:
      loop_var: sw
      
  
  - name: Making python scripts executable
    shell: find {{ dir }} -name '*.py' -exec chmod -c a+x {} \;
    loop:
      - /usr/local/rtws/commons-core/bin/boot
    loop_control:
      loop_var: dir
  
  - name: Ensuring python scripts do not have Windows line feeds
    shell: fromdos {{ dir }}/*.py
    loop:
      - /usr/local/rtws/commons-core/bin/boot
    loop_control:
      loop_var: dir
      
          
  - name: Making shell scripts executable
    shell: find {{ dir }} -name '*.sh' -exec chmod -c a+x {} \;
    loop:
      - /usr/local/rtws/commons-core/bin/boot
      - /usr/local/rtws/boot-apps/bin
      - /usr/local/rtws/cert-auth/bin
    loop_control:
      loop_var: dir
  
  - name: Ensuring shellscripts do not have Windows line feeds
    shell: fromdos {{ dir }}/*.sh
    loop:
      - /usr/local/rtws/commons-core/bin/boot
      - /usr/local/rtws/boot-apps/bin
      - /usr/local/rtws/cert-auth/bin
    loop_control:
      loop_var: dir
      
      
  # Setting up the cert environment
  - shell: /usr/local/rtws/cert-auth/bin/edit_sudoers.sh
    args:
      chdir: /usr/local/rtws/cert-auth/bin
  
  - shell: /usr/local/rtws/cert-auth/bin/setup_env.sh
    args:
      chdir: /usr/local/rtws/cert-auth/bin
      
  - name: Ensure /usr/local/rtws has the correct permissions
    file: path=/usr/local/rtws owner=rtws group=rtws mode=0775 state=directory recurse=yes