---
  - name: Adding the rtws group
    group: name=rtws gid=1001 state=present
      
  - name: Adding the rtws user
    user: name=rtws uid=1001 shell=/bin/bash createhome=no state=present group=rtws groups=
    
  - name: Adding the jetty group
    group: name=jetty gid=1003 state=present
      
  - name: Adding the jetty
    user: name=jetty uid=1003 shell=/bin/bash createhome=no state=present group=jetty groups=
    
  - name: Adding jetty to the rtws group
    user: name=jetty uid=1003 shell=/bin/bash createhome=no state=present group=jetty groups=rtws,jetty
  
  - file: path=/home/rtws owner=rtws group=rtws mode=0775 state=directory
     
  - file: path=/home/jetty/logs owner=jetty group=jetty mode=0755 state=directory recurse=yes