---
  - file: path=/usr/local/rtws/webapps-repository/conf owner=rtws group=rtws mode=0775 state=directory recurse=no
 
  - unarchive: src={{ rtws_appfs }}/release/{{ rtws_release }}/{{ sw }} dest=/usr/local/rtws
    loop:
      - deleidos-rtws-webapps-repository.tar.gz
    loop_control:
      loop_var: sw
      
  - unarchive: src={{ rtws_appfs }}/configuration/{{ rtws_domain }}//{{ sw }} dest=/usr/local/rtws/webapps-repository/conf
    loop:
      - deleidos-rtws-webapp-repository-conf.tar.gz
    loop_control:
      loop_var: sw
      
  - unarchive: src={{ rtws_appfs }}/release/{{ rtws_release }}/{{ sw }} dest=/usr/local/jetty/webapps
    loop:
      - deleidos-rtws-webapps-repository-webapp.tar.gz
      - deleidos-rtws-webapps-logapi-webapp.tar.gz
      - deleidos-rtws-webapps-caapi-webapp.tar.gz
    loop_control:
      loop_var: sw
      
  #- unarchive: src={{ rtws_appfs }}/configuration/{{ rtws_domain }}//{{ sw }} dest=/usr/local/jetty/webapps/logapi/WEB-INF/classes
  #  loop:
  #    - deleidos-rtws-webapp-logapi-conf.tar.gz
  #  loop_control:
  #    loop_var: sw
  
  - shell: /usr/local/jetty/bin/jetty_setup.sh
  
  - shell: find {{ dir }} -name '*.sh' -exec chmod -c a+x {} \;
    loop:
      - /usr/local/rtws/webapps-repository/bin
    loop_control:
      loop_var: dir
      
  - shell: find {{ dir }} -name '*.sh' -exec fromdos {} \;
    loop:
      - /usr/local/rtws/webapps-repository/bin
    loop_control:
      loop_var: dir
    
  - shell: /usr/local/rtws/commons-core/bin/boot/rtws_property_replace.pl /usr/local/rtws/properties/rtws-common.properties /usr/local/rtws/webapps-repository/bin/setup_repository.sh
  
  - shell: /usr/local/rtws/webapps-repository/bin/setup_repository.sh /usr/local/rtws/webapps-repository/conf

  - shell: /usr/local/rtws/commons-core/bin/boot/rtws_property_replace.pl /usr/local/rtws/properties/rtws-common.properties /usr/local/jetty/webapps/repository/WEB-INF/web.xml
  
  - shell: /usr/local/rtws/commons-core/bin/boot/rtws_property_replace.pl /usr/local/rtws/properties/rtws-common.properties /usr/local/jetty/webapps/repository/WEB-INF/templates/bootstrap.properties
  
  
  - name: Extracting release to /usr/local/rtws
    unarchive: src={{ rtws_appfs }}/release/{{ rtws_release }}/{{ sw }} dest=/usr/local/rtws/
    loop:
      - deleidos-rtws-ca-conf.tar.gz
    loop_control:
      loop_var: sw
      
  
  - name: Removing release tar.gz(s) 
    file: path={{ rtws_appfs }}/release/{{ rtws_release }}/{{ sw }} state=absent
    loop:
      - deleidos-rtws-ca-conf.tar.gz
    loop_control:
      loop_var: sw
      
  - shell: find {{ dir }} -name '*.sh' -exec chmod -c a+x {} \;
    loop:
      - /usr/local/rtws/ca/bin
    loop_control:
      loop_var: dir
  
  - shell: fromdos {{ dir }}/*.sh
    loop:
      - /usr/local/rtws/ca/bin
    loop_control:
      loop_var: dir 
      
  - shell: fromdos {{ dir }}/*.ca
    loop:
      - /usr/local/rtws/ca/conf
    loop_control:
      loop_var: dir    
      
      
      